name: "Build"


on:
  push:
    branches:
      - main
      - dev


jobs:
  linux-build:
    uses: ./.github/workflows/reusable_build.yml
    with:
      os: ubuntu-latest
      image: ghcr.io/lazypanda07/ubuntu_cxx20:24.04
      upload-artifact-name: Linux


  docker-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Build Docker image
      run: sudo docker build . -t ghcr.io/lazypanda07/vps_telegram_bot

    - name: Export Docker image
      run: docker save -o vps_telegram_bot.tar ghcr.io/lazypanda07/vps_telegram_bot

    - name: Upload Docker image
      uses: actions/upload-artifact@v6
      with:
        path: vps_telegram_bot.tar
