name: "Build"


on:
  push:
    branches:
      - main
      - dev


permissions:
  packages: write


jobs:
  linux-build:
    uses: ./.github/workflows/reusable_build.yml
    with:
      os: ubuntu-latest
      image: ghcr.io/lazypanda07/ubuntu_cxx20:24.04
      upload-artifact-name: Linux


  docker-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Build Docker image
      run: sudo docker build . -t ghcr.io/lazypanda07/vps_telegram_bot
      
    - name: Publish Docker image
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | sudo docker login ghcr.io -u LazyPanda07 --password-stdin
        sudo docker push ghcr.io/lazypanda07/vps_telegram_bot
